### ISSUE TITLE
Have geo location links not blindly parsed

### ISSUE THREAD

**Issue by mayurankv** [esm7/obsidian-map-view#120]
Currently, the geo location links `[](geo:lat,lon)` are parsed blindly within the markdown note as far as I can tell. I was attempting to create a dynamic map location using dataview and generating the exact same link in the preview pane using dataview doesn't show the note in the map whereas if I have a commented out location, the location still shows up in the map. It would be good to allow dataview blocks giving the required format to be read or dynamic templater commands.

As an example if I wanted a dynamic location given by the commands `<%+ tp.user.latlon %>` or `\`=this.latlon\`` where both give the string "[Ex](geo:0,0)", then I would expect both commands to be parsed into the map view.

I'm not 100% sure how this change would need to be implemented, I also saw previous discussion regarding the dataview api so this may go hand in hand?

Thank you

**Comment by esm7** [comment]
It basically means that Map View would need to communicate with the Dataview API when it sees an inline data query. This should be possible, but I think it requires a caching solution, because Map View can't ask the Dataview API about every embedded location every time it wants to build its markers (it would make everything way too slow).
So this is possible, but requires some meaningful investment, that I'm not sure I can personally find the time for (especially given the vast amount of improvements and ideas I have for Map View).
If that's a feature that many users find helpful, I hope someone can step in and work on it before I do!

**Comment by mayurankv** [comment]
Thanks for explaining. I wish I was well versed enough to do it myself, maybe sometime in the future! Hopefully someone else finds this useful as well but appreciate the thorough reply.

**Comment by mayurankv** [comment]
Managed to get round this with dataview and metaedit fyi.

**Comment by esm7** [comment]
Thanks, that's good to know! Would you mind elaborating a bit what you did in case others want to accomplish the same thing?

**Comment by mayurankv** [comment]
Just essentially using metaedits api in a dataviewjs block in order to change the location: parameter in metadata directly.
