### ISSUE TITLE
dataview and mapview 

### ISSUE THREAD

**Issue by dandobos** [esm7/obsidian-map-view#122]
Hi there. I have a question.

I have 3 types of notes: Literature Notes, Permanent Notes and Journal Entries.

Note on definitions that I use... 
Place: This is name of the place and I have various other inline fields like suburb, city, country to use later.
Location: These are the actual co-ordinates on the map eg [-33.11111,114.11111]

I love how map-view can with a shortcut produce inline location URLs. I'm using this feature.

However, I find that I also need to create a separate page for the place. So for each note I do the following....
Place: [[Location name (pl)]]
Location: [Location name](geo:-33.11111,114.11111)

Then I used dataview on [[Location name (pl)]] to show my various notes.

Everything works and it's great, it just feels like extra overhead to have both Place as well as Location.

I wonder if you ever contemplated this use case and if there is a way around it?

**Comment by esm7** [comment]
For this flow, and since you create a separate page for the place anyway, why use inline geolocations rather than stand-alone front-matter locations?
The `[[Location name (pl)]]` page can directly represent the location in its front matter without a geolocation link.
Just like you use the shortcut for an inline geolocation, you can use the "New geolocation note" command (I assigned it to Ctrl + M) or "Add geolocation (front matter) to current note". They both use the same search mechanism of the inline URLs.
Hope this helps!

**Comment by dandobos** [comment]
Thank you great observation, that is helpful.

The issue is that for frontmatter, I'd like to understand what it means, not just see random co-ordinates which are super confusing.

Is there a way to add a label to eg location: [-31.1111,141.11111]
To eg [Hudson River](geo:-31.1111,141.11111)

That last suggestions doesn't work in front matter, only inline.

I mean, I do have the name in the note, it's just not ideal to see random numbers that are meaningless.

**Comment by esm7** [comment]
I'm not using Dataview the same way you do, so I may be missing the mark here. But basically the concept of front matter fields is to add metadata to notes. So the name of note (e.g. Hudson River) should be the center here (and that's also what Map View shows you when hovering the marker), and you add to that various metadata, like its location.
The way I read it is that "Hudson River" (the note name) has "location" of the specified coordinates, and possibly other fields in the YAML front matter, that you may use with Dataview.
To my understanding adding a name to the location is redundant in this use case, because the location is a property of the object that the note is about.
Indeed the coordinates in the front matter don't mean anything visually by themselves, and that's possibly disturbing to you visually, but I think that the front matter isn't meant to always be human readable in the first place. (It's also hidden in Reading View.)

**Comment by dandobos** [comment]
My notes are about various concepts but the locations helps me remember them. The note is not about the location. It's not a big deal. I just use the inline location. Thank you for your feedback.
