### ISSUE TITLE
Open note after clicking always in same pane

### ISSUE THREAD

**Issue by Darkbluetest** [esm7/obsidian-map-view#129]
Hi

I have just noticed another thing that worked fine, but no more. When you have more than one pane open with notes (and they are not pinned), and I click in a marker on the map, it opens always in one of the panes, not in the pane I have selected. It worked fine before, but it has become "broken" at some update, just as the follow selected note thing.

And if the pane used by Map View to send the note of the marker, is closed, then even if you have other panes, Map View will not open (do nothing) when you click a marker... 

BTW, my suggestion here https://github.com/esm7/obsidian-map-view/issues/92#issuecomment-1145857042 is still valid (for me) and I think it would make the use smoother.

Thanks

**Comment by esm7** [comment]
Thank you for that, I think it broke because of the big Obsidian 1.0.0 UI changes, and I need to rework the code that selects the pane to open Map View on. (And add support to open in a new tab, while we're at it.)
If all goes roughly according to plan, I should have some meaningful time to work on Map View this month :crossed_fingers:

**Comment by Darkbluetest** [comment]
Thanks for reply! Let's hope things go well and as expected!

**Comment by esm7** [comment]
Fixed in 2.3.0 (not released yet).
