### ISSUE TITLE
Inline geolocation link name in map view

### ISSUE THREAD

**Issue by mSiotniHS** [esm7/obsidian-map-view#176]
I was wondering if it is possible to configure the plugin so that when I hover a marker in map view, I would see the name of inline geolocation link (`[Meaning this name](geo:...)`), not note name.

**Comment by esm7** [comment]
The immediate thing you can do is to use the (relatively new, so use a recent version of the plugin) setting "Show inline link name on marker hover". If you set it to "always", you will get the link name *in addition* to the note name.
If you truly wish to remove the note name, you can do so with a custom CSS, but I would recommend doing so only if you're absolutely sure that you're never using front matter geolocations, because there is no logic that decides to show it anyway if an inline name is not present.

**Comment by mSiotniHS** [comment]
Thanks! That resolves my issue.
