### ISSUE TITLE
Feature Request: Map paths

### ISSUE THREAD

**Issue by dlesbre** [esm7/obsidian-map-view#186]
Hi,

I like to use obsidian to record my hikes/road trips/etc. Pins are okay for this, but I would like to be able to draw a path on maps. I don't know if that is feasible/easy to do, but here are a few thoughts on the main points this feature should have:

- [ ] **Displaying path:**
  - [ ] Given a sequence of lat/long (possibly also elevation and time), can we display a path on the map view? 
  - [ ] (optional) fancy display option (color/width/thickness/...) customizable similarly to marker rules ? 
  - [ ] (optional) Quick filter option to show/hide all paths?
- [ ] **Paths in markdown:**
  - [ ] Probably only inline, in a block `mapview-path` 
  - [ ] List lat/long pairs in whatever syntax is most convenient (probably JSON)
    optionally with elevation and time info
  - [ ] Some extra data like tags, eventually one-off display options
  - [ ] (optional) It would be nice to have such blocks render as an embedded map centered on the path
- [ ] **Inputing paths:**
  - [ ] Manually input from map view: 
    Right-click > Context menu "start path", enters a "Path edit mode"
    In path edit mode, short left click adds a point to the current path
    In path edit mode, right-click menu has new entries: "Exit and create new note with path", "Exit and copy path", "Remove last point", "Exit"
  - [ ] (bonus) allow dragging points around in edit mode
  - [ ] (bonus) allow importing [GPX files](https://en.wikipedia.org/wiki/GPS_Exchange_Format), this allows import from sports apps which is neat

I might try to implement it at some point but I don't have much time and don't know much JS so no promises...

Thanks for maintaining this awesome plugin!

**Comment by esm7** [comment]
That's a highly requested feature -- I'll close it as a dup with https://github.com/esm7/obsidian-map-view/issues/50 and https://github.com/esm7/obsidian-map-view/issues/17.
Long story short, Map View is first and foremost a UI-centric tool (unlike Obsidian Leaflet, for example, which is code-block based). It will not introduce features without backing them up with a strong interactive user experience.
So although the basic functionality of displaying paths, reading them from GPX, GeoJSON etc is quite simple (due to being mostly handled by great Leaflet.js plugins), the full toolset required to build a proper user experience around this functionality requires a lot of work. As a bare minimum, we'd need a separate set of settings to format displayed routes based on some rules (similarly to markers but very different) and a different set of query controls and logic to filter routes (you surely don't want a large bunch of routes to be displayed on the map all the time).
That's all very doable, but not realistic in the time I can afford to invest right now :(
