### ISSUE TITLE
FR: Location tagging in notes using geotags instead of coordinates

### ISSUE THREAD

**Issue by HEmile** [esm7/obsidian-map-view#2]
Currently, you can give notes a location using 

```
---
location: [40.6892494,-74.0466891]
---
```

I often create notes specifically for locations, eg for streets and cities. Would it be possible to instead pass a string that will be queried to find the coordinates? For instance, 

```
---
location: "Amsterdam"
---
```
Would give the location of Amsterdam, for instance using `leaflet-geosearch`'s first hit. This is much quicker when editing than having to lookup the coordinates (eg, it can be automated easily using Templater from the title).

**Comment by esm7** [comment]
I really like the idea. But external search results must be cached and cache needs to be managed, so I'm wondering -- what do you think is better?
Option 1: cache results for `location: "Amsterdam"` in an auto-generated front-matter tag, e.g. `locationResult: [123.456,123.456]`.
Option 2: when typing `location: "`, open a popup with search results, and when you choose "Amsterdam", it would complete the coordinates and also log the search term for future readability, e.g. fill in `location: [123.456,123.456,"Amsterdam"]`

There's also the option of managing the cache externally (e.g. in data files) but I think writing it explicitly is more in-line with the Obsidian & Markdown notes philosophy.

**Comment by HEmile** [comment]
Great ideas! I **love** option 2, as it also allows disambiguating between similarly named locations. One additional suggestion would then be to create commands to insert location YAML tags or the inline location tag which would open a search popup modal. 
And indeed, explicitly in Markdown fits best.

**Comment by esm7** [comment]
What I *wanted* to do was a command that triggered an auto-complete popup menu for a location search.
But the days went by and I was unable to find time for it, so I did something more similar to what you originally asked. When right-clicking text in a note, you now have a "convert to location link" item. It geo-searches that name and converts the text to a geolink with the first match. (It also adds a note frontmatter if none exists, for convenience.)
There is also a command for that, so it can be mapped to a keyboard shortcut.
I still hope to make a suggestions popup at some point though, because although the first match is great most of the time, it can sometimes be in a whole different continent than what you meant :)
