### ISSUE TITLE
location: [xx, yy] - Interpreted as Title 🔤🔠🔡

### ISSUE THREAD

**Issue by Danielkaas94** [esm7/obsidian-map-view#210]
I tried this from your example, but it doesn't work, for some weird reason, it is interpreted as a huge Title? and no, there was no hashtags in my line

```
---
location: [40.6892494, -74.0466891]
---
```

**Comment by esm7** [comment]
I guess I need to update the readme, since the front matter works differently now.
If you use Obsidian's properties UI, you need to add a property named `location` and then add the value to it.
However, why do you need to add the `location` value manually? Map View has so many tools to do it for you, from "new geolocation note" commands to various map tools and "add geolocation" menu item in notes... I think I haven't added a front matter manually for over a year. Is there a specific workflow on which you find it needed?

**Comment by Danielkaas94** [comment]
❤🧡💛💚💙💜🤍💜💙💚💛🧡❤
Sorry! I am a n00b with this plugin 🙈
❤🧡💛💚💙💜🤍💜💙💚💛🧡❤

**Comment by javierseixas** [comment]
Hi! Same issue here. I used to create a note from the Calendar plugin, and insert the property location manually. In this way, Obsidian doesn't detect it's a geolocation, so the coordinate doesn't appear later in the map view.
How I can solve this?

**Comment by esm7** [comment]
Should be fixed as part of the just-released 5.0.0.
