### ISSUE TITLE
Empty map marker for certain emojis

### ISSUE THREAD

**Issue by quiyahui** [esm7/obsidian-map-view#233]
When using certain emojis, such as  "🏟️",  as a marker icon the marker is displayed empty. 

![image](https://github.com/esm7/obsidian-map-view/assets/43812426/e5ff7d68-b231-4214-99b9-ca1e9f63c453)

PS: A different minor issue is that the emoji in the marker popup is larger than on the map markers.

![image](https://github.com/esm7/obsidian-map-view/assets/43812426/50d7e8a5-66b1-48e6-911e-39a5d1260b32)

**Comment by esm7** [comment]
Wow indeed a bunch of issues here, will fix.

**Comment by esm7** [comment]
P.S: in case I'll have problems recreating the issues, can you elaborate what OS are you using? As a bare minimum -- Windows/Mac/Linux/Android/iOS?

**Comment by quiyahui** [comment]
I noticed both issues on Linux using the Default and/or Minimal theme. I haven't tested on another OS yet.

**Comment by esm7** [comment]
Fixed in 5.0.2.
As of the marker popup annoyance, well, I'll have to put that aside that for now -- getting all the types of icons look pixel-perfect on all the types of markers is a hassle :( I devoted all efforts to making everything look optimal on the map itself, and in other displays (the settings pane, the cluster preview and the search) there are a few small glitches.
