### ISSUE TITLE
Empty "Properties" section attached to each note when geolocation data is added

### ISSUE THREAD

**Issue by W1BTR** [esm7/obsidian-map-view#242]
![image](https://github.com/esm7/obsidian-map-view/assets/164893442/ef6642d3-e6a0-461e-9d2b-2f86ab248e7c)
Last stupid question for the day

Im wondering if there is any way to _not_ show this properties section when geodata is inserted into a note. I leave it blank as I typically will have a few geolocations in each note, and it significantly clutters up the note.

I also noticed when I click on the "location" field it suggests some geodata, but it's not a location saved in the note.
Cheers!

**Comment by esm7** [comment]
The problem is that Map View needs some hint about what notes include inline geolocations, so it wouldn't need to read the content of all your notes, which is very resource-intensive. The default way to do that is to add a `locations:` front matter entry.
There's also an alternative of using a tag -- search for "tag name to denote inline geolocations" in the README for more details. However it's not as great for two reasons: 1) It's slower (a slow-down of Map View can be felt if you have hundreds of locations), 2) Map View currently doesn't add this tag automatically, and you'll need to remove `locations:` and add that tag in your notes which can be annoying.

Maybe there are plugins that can hide some property fields from the display to reduce clutter? This can be a direction to look at.

**Comment by W1BTR** [comment]
I saw another plugin that used "Properties" and realized it was an Obsidian-based thing rather than a map-view thing. Sadly no such plugin exists at the moment but that's quite alright. May this be our biggest issue.

Thanks for the explanation and suggestion!
