### ISSUE TITLE
Preview doesn't work unless my curser is on geolink line

### ISSUE THREAD

**Issue by brunoprela** [esm7/obsidian-map-view#247]
Given a geolink, the preview doesn't show up on hover with the mouse only. I have to click on the line where the geolink is so that the geolink markdown formatting splits up and reveals itself ([](geo:)), and then I can hover over it for the preview to show up. The preview is such an amazing feature I would love if it worked on hover only. Amazing plugin btw!

**Comment by esm7** [comment]
Really happy that you like Map View and the preview feature :)
I can't recreate the issue, so can you elaborate how you are seeing it?
Also some details could help, most notably your Obsidian version, Map View plugin version, your OS, and whether you may be using some custom Obsidian theme.
Specifically testing things with the latest Obsidian, latest Map View and no custom theme can help narrow down the options of what the issue is.

**Comment by esm7** [comment]
Would you mind trying if the issue happens with all the other plugins turned off (and then restarting Obsidian)? It seems to me like the document is modified by something which makes it unrecognizable by the Map View editor plugin, but hard to pinpoint what it is.
