### ISSUE TITLE
Embedded map views cannot set `viewSettings`

### ISSUE THREAD

**Issue by zakj** [esm7/obsidian-map-view#263]
First, thank you so much for this plugin! I'd been using the Leaflet plugin for a while, but the UX here is really great.

I'd like hide some of the controls for some inline maps: I have a set of "city" notes, in which I like to embed an appropriately-centered/zoomed map that shows the relevant places for that city, and the controls can be a bit distracting. It looks like `ViewSettings.showEmbeddedControls` is intended for that, but I don't see a way to make it happen. E.g., changing the values for `showEmbeddedControls` and `showView` in this embed have no effect:

    ```mapview
    {
        "centerLat":0.1,
        "centerLng":0.1,
        "query":"",
        "chosenMapSource":0,
        "showEmbeddedControls":false,
        "showView":false
    }
    ```

It looks like `embeddedMap.EmbeddedMap` is [intended](https://github.com/esm7/obsidian-map-view/blob/master/src/embeddedMap.ts#L24) to support custom view settings, but the code block handler (where `EmbeddedMap` is instantiated) [does not pass that argument](https://github.com/esm7/obsidian-map-view/blob/master/src/main.ts#L200-L206).

Am I missing some way to do this? If not, would you be open to a PR and do you have strong opinions on the implementation approach?

**Comment by esm7** [comment]
Hi,
There is some conceptual problem here, as the Map View code block contains a `MapState` and not view settings.
Technically there is no problem to do what you're looking for (like you noticed, `EmbeddedMap` has the argument to do so, which was meant for `MapPreviewPopup` but can perfectly be used for embeds too). The only question is how it doesn't become patchy and fragile, as view settings won't be updated every time a state does, and we don't want them to be overwritten by map updates.
Seems to me like the best approach would be to parse an optional `customViewSettings` field in `registerMarkdownCodeBlockProcessor`, that will be added to the `MapState` type (with a comment saying this is only for `EmbeddedMap`, then pass it to the constructor of `EmbeddedMap` like you suggested. You can definitely go ahead with PR.
In the context you want it to work, I think it will provide nice flexibility that some advanced users can benefit from.
Note that it's not just about reading `customViewSettings` from the code block state object, but also about writing it there (otherwise it will be overwritten by map zoom/pan). In order to not add it to all users, please write it only if it already existed.

**Comment by zakj** [comment]
Thanks for the explanation and the implementation advice; both make sense! I'll find time next week to put something together.
