### ISSUE TITLE
Geolocations do not appear in "Map View", but do when clicking "Show On Map"

### ISSUE THREAD

**Issue by RalphMRivera** [esm7/obsidian-map-view#70]
Hi,

I added a Geolocation to a note like this:

```
**Address:** [6501 Railroad Ave, Snoqualmie, WA 98065](geo:47.54233444933289,-121.83649884956549)
```

When I right-click that link and select `Show on map` the result seems accurate, but the map is generated by **Open Street Map** and not **Google**. I have set my plugin to use **Google** and added an _API key_, but I can't get results generated by **Google**. The same is true when I click the `Map View` button on the left side; I don't see **Google**.

How can I get the maps generated with **Google**?

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1270019/162976700-051d5519-a24b-4b64-94e4-09b1bb54309c.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/1270019/162976898-f3b70b23-713f-4cb4-b3c1-ec4fea1cd685.png">

![image](https://user-images.githubusercontent.com/1270019/162977402-a4e6ac5d-4402-49f2-8bbc-b65fbcee1645.png)

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1270019/162977588-ebba1e28-09f0-4348-904c-9c6d6b388a5d.png">

**Comment by esm7** [comment]
Hi Ralph,
You configured Map View to use Google Maps as a **geocoding search provider**, which is the service used to translate text (e.g. addresses) to coordinates.
If you want to use Google Maps as a **map source**, you need to add it under the Map Sources section of the plugin and then switch to it in the View control on the map.
The problem is that I cannot help you find the URL for Google Maps tiles to be used with Leaflet, because I'm not sure the Google Maps terms of use allow me to, but you can easily find it over the Internet.
Hope this helps.
